config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :expenses, only: [:new, :create, :show, :index, :update, :edit]

  resources :user_expenses, only: [:update, :show] do
    post 'paid', on: :member
    member do
      post 'paid'
      post 'voucher'
    end
  end

  get '/convites/:token', to: 'expenses#invite', as: 'expense_invite'
  post '/convites/:token/aceitar', to: 'expenses#accept_invite',
                                   as: 'expense_invite_accepted'

  get 'user_root', to: 'expense#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :title, :description, :event_date, :pay_date, :total_price,
            :participants_amount,
            presence: true

  has_many :user_expenses
  has_many :users, through: :user_expenses
  has_secure_token

  has_attached_file :event_photo
  validates_attachment_content_type :event_photo,
                                    content_type: %r{\Aimage\/.*\z}

  def pricer_per_participant
    total_price / participants_amount
  end

  def owner
    user_expense = user_expenses.find_by(role: :owner)
    user_expense.user if user_expense
  end

  def owner?(user)
    owner == user
  end

  def payment_is_available?
    Date.today <= pay_date
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :user_expenses
  has_many :expenses, through: :user_expenses
end

app/models/user_expense.rb
class UserExpense < ApplicationRecord
  enum role: { owner: 0, participant: 1 }
  enum payment_status: { open: 0, paid: 1, pending: 2 }
  belongs_to :user
  belongs_to :expense
  has_attached_file :payment_voucher
  validates_attachment_content_type :payment_voucher,
                                    content_type: %r{\Aimage\/.*\z}

  def mark_as_pending
    pending! if payment_voucher.exists?
    pending?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    expenses_path
  end

  def after_sign_out_path_for(resource)
    expenses_path
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :invite, :show,
                                            :accept_invite]
  before_action :validate_invite, only: [:invite]

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)
    if @expense.save
      @expense.user_expenses.create(user: current_user, payment_status: :open,
                                    role: :owner)
      flash[:notice] = 'Rateio cadastrado com sucesso!'
      redirect_to expense_path @expense
    else
      render :new
    end
  end

  def invite
    @expense = Expense.find_by(token: params[:token])
    if UserExpense.find_by(user: current_user, expense: @expense)
      flash[:notice] = 'Você já está nesse rateio'
      redirect_to @expense
    else
      render :invite
    end
  end

  def accept_invite
    @expense = Expense.find_by(token: params[:token])
    @expense.user_expenses.create(user: current_user, payment_status: :open,
                                  role: :participant)
    redirect_to @expense
  end

  def show
    @expense = Expense.find(params[:id])
    @user_expenses = @expense.user_expenses
    @current_user_expense = current_user.user_expenses.find_by(
      expense: @expense
    )
  end

  def index
    @expenses = current_user.expenses
    flash[:alert] = 'Nenhum rateio cadastrado' if @expenses.empty?
  end

  def edit
    @expense = Expense.find(params[:id])
  end

  def update
    @expense = Expense.find(params[:id])
    if @expense.update(expense_params)
      flash[:notice] = 'Rateio atualizado com sucesso!'
      redirect_to expense_url @expense
    else
      render :new
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:title, :event_date, :pay_date,
                                    :total_price, :event_photo,
                                    :description, :participants_amount)
  end

  def validate_invite
    @expense = Expense.find_by(token: params[:token])

    return if @expense.payment_is_available?
    flash[:alert] = t('expenses.invite.expired')
    redirect_to expense_path(@expense)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    redirect_to expenses_path
  end
end

app/controllers/user_expenses_controller.rb
class UserExpensesController < ApplicationController
  before_action :authenticate_user!, only: [:update, :paid, :show]
  before_action :set_user_expense, only: [:update, :show, :paid, :voucher]
  before_action :validate_payment, only: [:voucher]

  def voucher
    @user_expense.update(voucher_params)
    flash[:notice] = if @user_expense.mark_as_pending
                       ExpenseMailer.payment_received(@user_expense.id)
                       t('user_expense.voucher.success')
                     else
                       t('user_expense.voucher.error')
                     end

    redirect_to expense_path(@user_expense.expense)
  end

  def show; end

  def paid
    redirect_to root_path unless @user_expense.expense.owner?(current_user)

    @user_expense.paid!
    redirect_to expense_path(@user_expense.expense)
  end

  private

  def set_user_expense
    @user_expense = UserExpense.find(params[:id])
  end

  def voucher_params
    params.require(:user_expense).permit(:payment_voucher)
  end

  def validate_payment
    set_user_expense

    return if @user_expense.expense.payment_is_available?
    flash[:alert] = t('user_expense.voucher.date_limit_exceded')
    redirect_to expense_path(@user_expense.expense)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/_expense.html.erb
<hr>
<div class="row">
<div class="col-md-6">
  <dl>
    <dt></dt>
    <dd><h2><%= link_to expense.title, expense_path(expense) %></h2></dd>

    <% if expense.event_photo.exists? %>
      <%= image_tag expense.event_photo.url, class:'img-thumbnail', width:'300px' %>
    <% end %>

    <dt>Organizador</dt>
    <dd><%= expense.owner.name %></dd>

    <dt>Link para convite</dt>
    <dd><%= link_to expense_invite_url(expense.token), expense_invite_url(expense.token) %></dd>
 </dl>
</div>

<div class="col-md-6">
<dl>
    <dt>Descrição</dt>
    <dd><%= expense.description %></dd>

    <dt>Data do evento</dt>
    <dd><%= I18n.l(expense.event_date) %></dd>

    <dt>Data do pagamento</dt>
    <dd><%= I18n.l(expense.pay_date) %></dd>

    <dt>Valor total</dt>
    <dd><%= number_to_currency(expense.total_price) %></dd>

    <dt>Número de participantes</dt>
    <dd><%= expense.participants_amount %></dd>

    <dt>Valor por participante</dt>
    <dd><%= number_to_currency(expense.pricer_per_participant) %></dd>

  </dl>
  <% if expense.owner? current_user%>

    <%= link_to 'Editar', edit_expense_path(expense), class: 'btn btn-warning' %>

  <% end %>
</div>
<hr>
</div>

app/views/expenses/_form.html.erb
<% if @expense.errors.any? %>
  <div class="alert-danger">
    <% @expense.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  </div>
<% end %>
<%= simple_form_for @expense do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :event_date %>
  <%= f.input :pay_date %>
  <%= f.input :total_price %>
  <%= f.input :participants_amount %>
  <%= f.input :event_photo %>
  <div class="action">
    <%= f.button :submit, class:'btn btn-warning' %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<div class="row">
  <h1><%= t('.title') %>: <%= @expense.title %></h1>
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <%= render 'form' %>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/expenses/index.html.erb
<%= render @expenses %>

app/views/expenses/invite.html.erb
<%= link_to 'Aceitar convite', expense_invite_accepted_path(@expense.token), method: :post, class: 'btn btn-primary' %>

app/views/expenses/new.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <h1><%= t('.title') %></h1>
  <div class="col-md-8">
    <%= render 'form' %>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/expenses/show.html.erb
<%= render @expense %>
<hr><br>
<% if @current_user_expense.open? %>
  <%= simple_form_for @current_user_expense, url: voucher_user_expense_path(@current_user_expense), html: { multipart: true, method: :post, id: 'payment_form' } do |form| %>
    <legend>Envie aqui seu comprovante do pagamento:</legend>
    <%= form.input :payment_voucher %>
    <%= form.button :submit %>
    <%= form.input_field :id, as: :hidden %>
  <% end %>
<% end %>
<hr><br>

<h2>Participantes</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Status de Pagamento</th>
      <th scope="col">Comprovante de Pagamento</th>
      <th scope="col">Ação</th>
    </tr>
  </thead>
  <tbody>
    <% @user_expenses.each do |user_expense| %>
      <tr>
        <td><%= user_expense.user.name %></td>
        <td id='<%= "status_#{ user_expense.user.id }" %>'><%= t(user_expense.payment_status) %></td>
        <td id='<%= "receipt_#{ user_expense.user.id }" %>'>
          <% if !user_expense.open? && (current_user == user_expense.user || current_user == @expense.owner) %>
            <%= link_to 'Comprovante de pagamento', user_expense_path(user_expense) %>
          <% end %>
        </td>
        <td id='<%= "action_expense_#{ user_expense.user.id }" %>'>
          <% if (user_expense.open? || user_expense.pending? ) && current_user == @expense.owner %>
            <%= link_to 'Confirmar', paid_user_expense_path(user_expense), method: 'post' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rateio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand">
            <%= image_tag("logo.jpg") %>
            Rateio
          </a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Criar Rateio', new_expense_path, class: 'nav-link' %>
            </li>
            <% if !user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Entrar', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Cadastrar', new_user_registration_path, class: 'nav-link' %>
              </li>
            <% else %>
            <li class="nav-item">
              <%= link_to 'Meus Rateios', expenses_path, class: 'nav-link' %>
            </li>
              <li class="nav-item">
                <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  <div class="container-fluid">
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-info"><%= notice %></div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/user_expenses/show.html.erb
<h1>Comprovante de pagamento de <%= @user_expense.user.name %></h1>

<%= image_tag @user_expense.payment_voucher.url %>

<%= link_to 'Voltar para o rateio', expense_path(@user_expense.expense) %>